{% set name = "dfvue" %}
{% set version = "1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dfvue-{{ version }}.tar.gz
  sha256: 6eb61f045bb78cfb7afdc85eb30631e8723771a293b46870a6b6c635b5a6fbf7

build:
  number: 0
  noarch: python
  entry_points:
    - dfvue = dfvue.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=42
    - setuptools_scm >=3.5
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - pandas
    - customtkinter
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]
    - tk       # [linux]

test:
  imports:
    - dfvue  # [not linux]
  commands:
    - xvfb-run --auto-servernum python -c "import dfvue"  # [linux]

app:
    entry: python -m dfvue
    icon: dfvue_icon.png
    summary: dfvue - a minimal GUI for a quick view of csv files
    type: desk
    own_environment: True

about:
  home: https://github.com/mcuntz/dfvue
  summary: 'A minimal GUI for a quick view of csv files'
  dev_url: https://github.com/mcuntz/dfvue
  license: MIT
  license_file: LICENSE
  description: |
    dfvue is a minimal GUI for a quick view of csv files. It uses an input
    panel similar to Excel to check visually that the csv file is read
    correctly. It provides most options of pandas.read_csv to be very
    versatile on possible csv formats. dfvue is a Python script that can be
    called from within Python or as a command line tool. It is not supposed
    to produce publication-ready plots but rather provide a quick overview
    of the csv file.
  doc_url: https://mcuntz.github.io/dfvue

extra:
  recipe-maintainers:
    - mcuntz
